//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MunicipalityTax
    {
        public int Id { get; set; }
        public int MunicipalityId { get; set; }
        public int TaxTypeId { get; set; }
        public decimal TaxValue { get; set; }
        public System.DateTime PeriodStartDate { get; set; }
        public System.DateTime PeriodEndDate { get; set; }
    }
}
